---
- name: Perform nslookup
  hosts: all
  gather_facts: true

  tasks:
    - name: Run nslookup command
      shell: dns ansible  # Replace 'your_client_name' and 'your_nameserver' with actual values
      register: nslookup_output

    - name: Display nslookup results
      debug:
        var: nslookup_output.stdout_lines

- name: Read /etc/resolv.conf
  hosts: all
  gather_facts: true

  tasks:
    - name: Read /etc/resolv.conf content
      shell: cat /etc/resolv.conf
      register: resolv_conf_output

    - name: Display /etc/resolv.conf content
      debug:
        var: resolv_conf_output.stdout_lines

- name: Add custom nameserver to /etc/resolv.conf
  hosts: all
  gather_facts: true

  tasks:
    - name: Add nameserver entry to /etc/resolv.conf
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver your_custom_nameserver"  # Replace 'your_custom_nameserver' with the actual nameserver IP you want to add
        state: present
        insertafter: EOF
      become: true
      when: ansible_distribution == 'Centos7'  # Adjust this condition based on the OS distribution on your target hosts

